spring:
  datasource:
    url: ${DB_URL:jdbc:sqlserver://host.docker.internal:1433;databaseName=DB_LMS;encrypt=false;trustServerCertificate=true}
    username: ${DB_USERNAME:lms_app}
    password: ${DB_PASSWORD:}
