name: Java CI

on:
  push:
    branches:
      - "feature/**"
      - "release"
      - "main"

  pull_request:
    branches:
      - "release"
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v6

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build e testes
        run: mvn clean verify
